### ISSUE TITLE
Run on GPU Device

### ISSUE THREAD

**Issue by filipppp** [alex04072000/ObstructionRemoval#12]
Trying to do the fence removal on my Graphics Card, I tried it with the command provided in the README.md. I verified my CUDA and Nvidia drivers installation and I can run tensorflow operations on my gpu. 

I even changed line 43 & 44 in test_fence.py to GPU instead of CPU and it still doesnt use the gpu.

Can you guys provide a guide on how to use this with the GPU?

**Comment by vladimircape** [comment]
> Trying to do the fence removal on my Graphics Card, I tried it with the command provided in the README.md. I verified my CUDA and Nvidia drivers installation and I can run tensorflow operations on my gpu.
> 
> I even changed line 43 & 44 in test_fence.py to GPU instead of CPU and it still doesnt use the gpu.
> 
> Can you guys provide a guide on how to use this with the GPU?

they had an error in the code. for example In test_fence.py please change
nn_opts['gpu_devices'] = ['/device:CPU:0'] to nn_opts['gpu_devices'] = ['/device:GPU:0']
and os.environ["CUDA_VISIBLE_DEVICES"] = GPU_ID to os.environ["CUDA_VISIBLE_DEVICES"] = "0" . but the model is need more than 4Gb of GPU memory. 4gb is not enough

**Comment by vladimircape** [comment]
tensorflow-gpu==1.15.4 tqdm pandas matplotlib numpy scikit-image should be. And use linux

**Comment by filipppp** [comment]
Thanks! Will have to try out when new GPU arrives :+1:
