### ISSUE TITLE
ModuleNotFoundError: No module named 'ckpt_mgr'

### ISSUE THREAD

**Issue by aa12356jm** [alex04072000/ObstructionRemoval#2]
`Traceback (most recent call last):
  File "train_reflection_online.py", line 45, in <module>
    from model_pwcnet import ModelPWCNet, _DEFAULT_PWCNET_TEST_OPTIONS
  File "tfoptflow/tfoptflow/model_pwcnet.py", line 18, in <module>
    from model_base import ModelBase
  File "tfoptflow/tfoptflow/model_base.py", line 16, in <module>
    from ckpt_mgr import BestCheckpointSaver
ModuleNotFoundError: No module named 'ckpt_mgr'`

**Comment by alex04072000** [comment]
You need to git clone the [PWC-Net](https://github.com/philferriere/tfoptflow) and pre-trained weight and overwrite `tfoptflow/model_pwcnet.py` and `tfoptflow/model_base.py` in this repository.
Please refer to a working [colab](https://colab.research.google.com/drive/1nPEnD1aa7NvsLHoW_GfwcZtREXEa_n8o) for reference.

**Comment by aa12356jm** [comment]
thanks

**Comment by k4rth33k** [comment]
The [colab ](https://colab.research.google.com/drive/1nPEnD1aa7NvsLHoW_GfwcZtREXEa_n8o)gives this error while running the fence_demo file. The model doesn't seem to be present in the needed folder.
`ValueError: The passed save_path is not a valid checkpoint: tfoptflow/tfoptflow/models/pwcnet-lg-6-2-multisteps-chairsthingsmix/pwcnet.ckpt-595000`

**Comment by reyking** [comment]
> The [colab ](https://colab.research.google.com/drive/1nPEnD1aa7NvsLHoW_GfwcZtREXEa_n8o)gives this error while running the fence_demo file. The model doesn't seem to be present in the needed folder.
> `ValueError: The passed save_path is not a valid checkpoint: **_tfoptflow/tfoptflow/models/pwcnet-lg-6-2-multisteps-chairsthingsmix/_**pwcnet.ckpt-595000`

go inside that folder there is a link to de model

**Comment by fpjr** [comment]
The `wget` cell must be placed before the `python` cell. Moreover, the command should be `!wget` not `$ wget`, and the output path `tfoptflow/tfoptflow/models/pwcnet-lg-6-2-multisteps-chairsthingsmix/pwcnet.ckpt-595000.index`
