### ISSUE TITLE
Error while testing (ValueError: The passed save_path is not a valid checkpoint)

### ISSUE THREAD

**Issue by hana9090** [alex04072000/ObstructionRemoval#3]
Thank you for sharing this great work. I followed your instructions and tried to run 
`CUDA_VISIBLEDEVICES=0 python3 run_reflection.py`

But I got this error:
`ValueError: The passed save_path is not a valid checkpoint: temp_online_ckpt/model.ckpt-1000`

![image](https://user-images.githubusercontent.com/2920520/80246404-087e1e00-8675-11ea-8ac3-4c614ec0d123.png)

**I am wondering if I need to test the model on only one photo, then I need to run train fun? I need only to make prediction. is that possible?** 

Thanks

**Comment by ilnmtlbnm** [comment]
Hello @hana9090,

I had the same issue.
Seems like the checkpoint is actually `temp_online_cktp/model.ckpt-0`

You just need to edit `test_reflexion.py` and change line 23 to reflect this.

**Comment by hana9090** [comment]
Thank you @ilnmtlbnm :) it works now

I directly execute the following command:
`python3 test_reflection.py --test_dataset_name imgs/00002  --img_type  png --ckpt_path  ckpt_reconstruction_reflection/model.ckpt --output_dir  output`
